server:
  port: 8080
  read_timeout: 10s
  write_timeout: 30s

db:
  host: localhost
  port: 5432
  user: postgres
  password: password
  name: shop
  ssl_mode: disable

jwt:
  secret_key: change_me
  token_expiry: 24h
