CREATE TABLE IF NOT EXISTS user (
	id SERIAL PRIMARY KEY,
	username VARCHAR(50) UNIQUE NOT NULL,
	password TEXT NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS coin (
	id SERIAL PRIMARY KEY,
	balance INT NOT NULL DEFAULT 1000
);

CREATE TABLE IF NOT EXISTS item (
	id SERIAL PRIMARY KEY,
	name VARCHAR(30) UNIQUE NOT NULL, 
	price INT NOT NULL
);

CREATE TABLE IF NOT EXISTS inventory (
	id SERIAL PRIMARY KEY
	user_id INT REFERENCE user(id) ON DELETE CASCADE,
	item_id INT REFERECE item(id) ON DELETE CASCADE,
	quantity INT NOT NULL CHECK (quantity >= 0),
	UNIQUE (user_id, item_id)
);

CREATE TABLE IF NOT EXISTS transaction (
	id SERIAL PRIMARY KEY
	sender_id INT REFERENCE user(id) ON DELETE SET NULL,
	reciver_id INT REFERENCE user(id) ON DELETE SET NULL,
	amount INT NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE auth_token (
	id SERIAL PRIMARY KEY
	user_id INT REFERENCE user(id) ON DELETE CASCADE,
	token TEXT NOT NULL UNIQUE,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
