CREATE TABLE IF NOT EXISTS users (
	id SERIAL PRIMARY KEY,
	username VARCHAR(50) UNIQUE NOT NULL,
	password TEXT NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_users_username ON users(username);

CREATE TABLE IF NOT EXISTS coins (
	user_id INT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
	balance INT NOT NULL DEFAULT 1000
);

CREATE TABLE IF NOT EXISTS item (
	id SERIAL PRIMARY KEY,
	name VARCHAR(50) UNIQUE NOT NULL,
	price INT NOT NULL
);

CREATE TABLE IF NOT EXISTS inventory (
	id SERIAL PRIMARY KEY,
	user_id INT REFERENCES users(id) ON DELETE CASCADE,
	item_id INT REFERENCES item(id) ON DELETE CASCADE,
	quantity INT NOT NULL CHECK (quantity >= 0),
	UNIQUE (user_id, item_id)
);

CREATE TABLE IF NOT EXISTS transaction (
	id SERIAL PRIMARY KEY,
	sender_id INT REFERENCES users(id) ON DELETE SET NULL,
	receiver_id INT REFERENCES users(id) ON DELETE SET NULL,
	amount INT NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS auth_token (
	id SERIAL PRIMARY KEY,
	user_id INT REFERENCES users(id) ON DELETE CASCADE,
	token TEXT NOT NULL UNIQUE,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
